<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\UtilityTools.Core\UtilityTools.Core.csproj" />
		<ProjectReference Include="..\..\UtilityTools\UtilityTools.csproj" />
	</ItemGroup>

	<Target Name="CopyTargetFiles" AfterTargets="PostBuildEvent">
		<ItemGroup>
			<SomeFiles Include="$(OutDir)$(TargetFileName)" />
		</ItemGroup>
		<Copy SourceFiles="@(SomeFiles)" DestinationFolder="$(SolutionDir)UtilityTools\bin\$(ConfigurationName)\$(TargetFramework)\Modules\" SkipUnchangedFiles="true" />
	</Target>
</Project>
