<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <Target Name="CopyTargetFiles" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <SomeFiles Include="$(OutDir)$(TargetFileName)" />
    </ItemGroup>
    <Copy SourceFiles="@(SomeFiles)" DestinationFolder="$(SolutionDir)UtilityTools\bin\$(ConfigurationName)\$(TargetFramework)\Modules\" SkipUnchangedFiles="true" />
  </Target>

  <ItemGroup>
    <ProjectReference Include="..\..\Services\UtilityTools.Services.Interfaces\UtilityTools.Services.Interfaces.csproj" />
    <ProjectReference Include="..\..\Services\UtilityTools.Services\UtilityTools.Services.csproj" />
    <ProjectReference Include="..\..\UtilityTools.Core\UtilityTools.Core.csproj" />
  </ItemGroup>
</Project>
