<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <Target Name="CopyTargetFiles" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <SomeFiles Include="$(OutDir)$(TargetFileName)" />
    </ItemGroup>
    <Copy SourceFiles="@(SomeFiles)" DestinationFolder="$(SolutionDir)UtilityTools\bin\$(ConfigurationName)\$(TargetFramework)\Modules\" SkipUnchangedFiles="true" />
  </Target>

  <ItemGroup>
    <ProjectReference Include="..\..\UtilityTools.Core\UtilityTools.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CoreTools">
      <HintPath>bin\Debug\net6.0-windows\CoreTools.dll</HintPath>
    </Reference>
    <Reference Include="Devices">
      <HintPath>bin\Debug\net6.0-windows\Devices.dll</HintPath>
    </Reference>
    <Reference Include="Zem15C.CoreControl">
      <HintPath>bin\Debug\net6.0-windows\Zem15C.CoreControl.dll</HintPath>
    </Reference>
    <Reference Include="ZemModel">
      <HintPath>bin\Debug\net6.0-windows\ZemModel.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
