<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <Target Name="CopyTargetFiles" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <SomeFiles Include="$(OutDir)$(TargetFileName)" />
    </ItemGroup>
    <Copy SourceFiles="@(SomeFiles)" DestinationFolder="$(SolutionDir)UtilityTools\bin\$(ConfigurationName)\$(TargetFramework)\Modules\" SkipUnchangedFiles="true" />
  </Target>

  <ItemGroup>
    <ProjectReference Include="..\..\UtilityTools.Core\UtilityTools.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Zeptools.CommonLib">
      <HintPath>..\..\..\..\..\work\zeptools-basiclibrary\Zeptools.ControlLib\bin\Debug\net6.0\Zeptools.CommonLib.dll</HintPath>
    </Reference>
    <Reference Include="Zeptools.ControlLib">
      <HintPath>..\..\..\..\..\work\zeptools-basiclibrary\Zeptools.ControlLib\bin\Debug\net6.0\Zeptools.ControlLib.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
