<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Extended.Wpf.Toolkit" Version="4.5.1" />
    <PackageReference Include="MaterialDesignColors" Version="2.1.4" />
    <PackageReference Include="MaterialDesignThemes" Version="4.9.0" />
    <PackageReference Include="MetadataExtractor" Version="2.8.1" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.20.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.27" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.27" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.27" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NLog" Version="5.2.8" />
    <PackageReference Include="NLog.Extensions.Logging" Version="5.3.8" />
    <PackageReference Include="OpenCvSharp4" Version="4.10.0.20241108" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.9.0.20240103" />
    <PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.9.0.20240103" />
    <PackageReference Include="OxyPlot.Wpf" Version="2.1.2" />
    <PackageReference Include="Prism.DryIoc" Version="8.1.97" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
    <PackageReference Include="System.Management" Version="8.0.0" />
    <PackageReference Include="Zeptools.BseControlLib" Version="1.0.1" />
    <PackageReference Include="Zeptools.CCSControlLib" Version="1.0.2" />
    <PackageReference Include="Zeptools.CommonLib" Version="1.1.3" />
    <PackageReference Include="Zeptools.ControlLib" Version="1.0.4" />
    <PackageReference Include="Zeptools.Core.CoreTools" Version="2.0.0" />
    <PackageReference Include="Zeptools.Core.Devices" Version="2.0.0" />
    <PackageReference Include="Zeptools.Core.ZemModel" Version="2.0.0" />
    <PackageReference Include="Zeptools.DacControlLib" Version="1.0.1" />
    <PackageReference Include="Zeptools.EthControlLib" Version="1.0.1" />
    <PackageReference Include="Zeptools.FanControllib" Version="1.0.1" />
    <PackageReference Include="Zeptools.Hardware.Zeptools.CoreControl" Version="2.0.0" />
    <PackageReference Include="Zeptools.LedControlLib" Version="1.0.0" />
    <PackageReference Include="Zeptools.RelayControlLib" Version="1.0.0" />
    <PackageReference Include="Zeptools.ScanControlLib" Version="1.0.0" />
    <PackageReference Include="Zeptools.SeControlLib" Version="1.0.0" />
    <PackageReference Include="Zeptools.TempControlLib" Version="1.0.0" />
    <PackageReference Include="Zeptools.UartControlLib" Version="1.0.0" />
    <PackageReference Include="Zeptools.VacuumLib" Version="1.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\UtilityTools.Core\UtilityTools.Core.csproj" />
    <ProjectReference Include="..\Services\UtilityTools.Services.Interfaces\UtilityTools.Services.Interfaces.csproj" />
    <ProjectReference Include="..\Services\UtilityTools.Services\UtilityTools.Services.csproj" />
    <ProjectReference Include="..\UtilityTools.UserControls\UtilityTools.UserControls.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ContentWithTargetPath Include="$(SolutionDir)UtilityTools\bin\$(ConfigurationName)\$(TargetFramework)\Modules\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <TargetPath>Modules/%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </ContentWithTargetPath>
  </ItemGroup>
</Project>