<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UtilityTools.Core\UtilityTools.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Expression.Drawing">
      <HintPath>..\..\Third\Microsoft.Expression.Drawing.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
