<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
	  <PackageReference Include="Extended.Wpf.Toolkit" Version="4.5.1" />
	  <PackageReference Include="MaterialDesignColors" Version="2.1.4" />
	  <PackageReference Include="MaterialDesignThemes" Version="4.9.0" />
	  <PackageReference Include="OxyPlot.Wpf" Version="2.1.2" />
    <PackageReference Include="Prism.Wpf" Version="8.1.97" />
  </ItemGroup>
  <ItemGroup>
	<ProjectReference Include="..\..\Services\UtilityTools.Services.Interfaces\UtilityTools.Services.Interfaces.csproj" />
    <ProjectReference Include="..\..\UtilityTools.Core\UtilityTools.Core.csproj" />
  </ItemGroup>
	<Target Name="CopyTargetFiles" AfterTargets="PostBuildEvent">
		<ItemGroup>
			<SomeFiles Include="$(OutDir)$(TargetFileName)" />
		</ItemGroup>
		<Copy SourceFiles="@(SomeFiles)" DestinationFolder="$(SolutionDir)UtilityTools\bin\$(ConfigurationName)\$(TargetFramework)\Modules\" SkipUnchangedFiles="true" />
	</Target>
</Project>