<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Model\1e0jvahq.hwy~" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MaterialDesignColors" Version="2.1.4" />
    <PackageReference Include="MaterialDesignThemes" Version="4.9.0" />
    <PackageReference Include="Prism.Core" Version="8.1.97" />
    <PackageReference Include="Prism.Wpf" Version="8.1.97" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Services\UtilityTools.Services.Interfaces\UtilityTools.Services.Interfaces.csproj" />
    <ProjectReference Include="..\..\UtilityTools.Core\UtilityTools.Core.csproj" />
  </ItemGroup>
</Project>