<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\UtilityTools.Core\UtilityTools.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OxyPlot.Core" Version="2.1.2" />
    <PackageReference Include="OxyPlot.Wpf" Version="2.1.2" />
  </ItemGroup>
  <Target Name="CopyTargetFiles" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <SomeFiles Include="$(OutDir)$(TargetFileName)" />
    </ItemGroup>
    <Copy SourceFiles="@(SomeFiles)" DestinationFolder="$(SolutionDir)UtilityTools\bin\$(ConfigurationName)\$(TargetFramework)\Modules\" SkipUnchangedFiles="true" />
  </Target>
</Project>
