<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  
  <Target Name="CopyTargetFiles" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <SomeFiles Include="$(OutDir)$(TargetFileName)" />
    </ItemGroup>
    <Copy SourceFiles="@(SomeFiles)" DestinationFolder="$(SolutionDir)UtilityTools\bin\$(ConfigurationName)\$(TargetFramework)\Modules\" SkipUnchangedFiles="true" />
  </Target>
  
  <ItemGroup>
    <ProjectReference Include="..\..\UtilityTools.Core\UtilityTools.Core.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <Resource Include="CoarseFocusModelResources\model.onnx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
