<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="5.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\UtilityTools.Core\UtilityTools.Core.csproj" />
    <ProjectReference Include="..\UtilityTools.Services.Interfaces\UtilityTools.Services.Interfaces.csproj" />
  </ItemGroup>

</Project>
